### ISSUE TITLE
Certs path isn't available at repo

### ISSUE THREAD

**Issue by iamtorsten** [tsenger/animamea#2]
Path certs/PersoSim... isn't included in this repository.
![screen](https://cloud.githubusercontent.com/assets/19864638/22247807/e9111990-e23b-11e6-8fa8-b1085c1593fd.jpg)

**Comment by tsenger** [comment]
That's correct. I should remove the hardcoded paths.
You have to insert the path to your valid certificates to access the card here.

**Comment by tsenger** [comment]
Certificates were added in commit  51fe680
