### ISSUE TITLE
No card reader.

### ISSUE THREAD

**Issue by iamtorsten** [tsenger/animamea#4]
System can't establish connection to card reader on 64bit OS.

**Comment by iamtorsten** [comment]
libpcsclite.so.1 is in wrong directory on 64bit OS. You have to tweak manually.

sudo mkdir /usr/lib64
sudo ln -s /lib/x86_64-linux-gnu/libpcsclite.so.1 /usr/lib64/libpcsclite.so

**Comment by tsenger** [comment]
This is an OS depending issue. Can't do anything about it in animamea.

**Comment by iamtorsten** [comment]
Yes but i think it is worth to add this in your project description.
